/*
 * Narration for the demo video.
 *
 * The video is silent by construction: every frame is a pure function of `t`, and the captions carry
 * the argument. That is fine on a page and thin in a judging queue, where a video with no audio reads
 * as an unfinished one. This script gives the render a voice track without touching the picture.
 *
 * The narration is not written separately from the captions, because a second script is a second thing
 * that can drift. It is *derived* from `record/out/timeline.v2.json`, which the renderer writes: one
 * spoken line per caption, at the caption's own cue time. If a caption changes, the narration changes
 * with it on the next run, and the words on screen and the words in the ear cannot disagree.
 *
 * Two ways to get the audio for those lines:
 *
 *   NARRATE_VOICE=say   (default) macOS `say` synthesises each line offline. Immediate, reproducible,
 *                       and audibly synthetic: the system voices available here are the old
 *                       concatenative ones, not the neural voices.
 *   NARRATE_VOICE=human reads `record/narration/NN.wav|aiff|m4a|mp3` if present, one file per line
 *                       index, and falls back to `say` for any line not recorded yet. Record against
 *                       `docs/NARRATION.md`, which this script also writes.
 *
 * Either way the mix is the same: each line is delayed to its cue with `adelay`, the lines are summed
 * with `amix`, and the result is muxed onto the existing mp4 with `-c:v copy`. The picture is never
 * re-encoded, so adding audio cannot change a single frame of the video that was verified.
 *
 * Usage:
 *   npm run record:narrate                      # writes docs/NARRATION.md and the narrated mp4
 *   NARRATE_VOICE=human npm run record:narrate  # same, preferring recorded takes
 *   NARRATE_SCRIPT_ONLY=1 npm run record:narrate
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const OUT = join(ROOT, "record", "out");
const TAKES = join(ROOT, "record", "narration");
const WORK = join(OUT, "narration-work");

const CUT = process.env.NARRATE_CUT ?? "v2";
const TIMELINE = join(OUT, CUT === "v2" ? "timeline.v2.json" : "timeline.json");
const VIDEO_IN = join(OUT, CUT === "v2" ? "sentinel-demo-video.mp4" : "sentinel-demo.mp4");
const VIDEO_OUT = join(OUT, CUT === "v2" ? "sentinel-demo-video-narrated.mp4" : "sentinel-demo-narrated.mp4");
const MODE = (process.env.NARRATE_VOICE ?? "say").toLowerCase();
const SAY_VOICE = process.env.NARRATE_SAY_VOICE ?? "Samantha";

const ffmpeg = process.env.FFMPEG ?? "/opt/homebrew/bin/ffmpeg";
const ffprobe = process.env.FFPROBE ?? "/opt/homebrew/bin/ffprobe";

type Caption = { t0: number; t1: number; kicker?: string; html?: string; detail?: string };
type Line = { i: number; at: number; window: number; text: string; kicker: string };

/* The caption registers are HTML because they are rendered into a page. Spoken, they are one sentence:
 * tags carry emphasis that a voice carries by itself, and an entity read aloud is a bug. */
function speakable(html: string): string {
  return html
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "and")
    .replace(/&nbsp;/g, " ")
    .replace(/&lt;/g, "")
    .replace(/&gt;/g, "")
    .replace(/·/g, ",")
    .replace(/\s+/g, " ")
    .trim();
}

const timeline = JSON.parse(readFileSync(TIMELINE, "utf8")) as { duration: number; captions: Caption[] };

const lines: Line[] = timeline.captions
  .map((c, i) => ({
    i,
    at: c.t0,
    window: Math.max(0.5, c.t1 - c.t0),
    kicker: c.kicker ?? "",
    text: speakable(c.html ?? ""),
  }))
  .filter((l) => l.text.length > 0);

/* ------------------------------------------------------------------ the script, for a human to read */

const md: string[] = [
  "# Narration script",
  "",
  "Derived from `record/out/timeline.v2.json` by `npm run record:narrate`, so it cannot drift from the",
  "captions on screen: one spoken line per caption, at the caption's own cue time. Do not edit this file.",
  "Change a caption in `record/player/edit.v2.mjs`, re-render, and re-run the script.",
  "",
  "**To record it yourself.** One file per line, named by the index below, into `record/narration/`:",
  "`00.wav`, `01.wav`, and so on (`.aiff`, `.m4a` and `.mp3` also work). Leave out any line you do not",
  "want to read and it is synthesised instead. Then:",
  "",
  "```sh",
  "NARRATE_VOICE=human npm run record:narrate",
  "```",
  "",
  "The **window** column is how long that caption is on screen. A take longer than its window still",
  "works, it just overlaps the next line, so read to the window where you can.",
  "",
  "| # | cue | window | line |",
  "|---|---|---|---|",
  ...lines.map(
    (l) =>
      `| \`${String(l.i).padStart(2, "0")}\` | ${l.at.toFixed(1)}s | ${l.window.toFixed(1)}s | ${l.kicker ? `*${l.kicker}.* ` : ""}${l.text} |`,
  ),
  "",
  `${lines.length} lines over ${timeline.duration.toFixed(1)}s.`,
  "",
];
writeFileSync(join(ROOT, "docs", "NARRATION.md"), md.join("\n"));
console.log(`narration script  docs/NARRATION.md  ${lines.length} lines`);

if (process.env.NARRATE_SCRIPT_ONLY) process.exit(0);

/* ------------------------------------------------------------------------------- synthesise and mix */

if (!existsSync(VIDEO_IN)) {
  console.error(`no render at ${VIDEO_IN}. Run: RENDER_CUT=${CUT} npm run record:render`);
  process.exit(1);
}

rmSync(WORK, { recursive: true, force: true });
mkdirSync(WORK, { recursive: true });

function duration(file: string): number {
  const out = execFileSync(ffprobe, [
    "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", file,
  ]);
  return Number(String(out).trim());
}

const TAKE_EXT = ["wav", "aiff", "aif", "m4a", "mp3"];
function recordedTake(i: number): string | null {
  if (MODE !== "human") return null;
  const stem = String(i).padStart(2, "0");
  for (const ext of TAKE_EXT) {
    const p = join(TAKES, `${stem}.${ext}`);
    if (existsSync(p)) return p;
  }
  return null;
}

/* `say` has no way to ask for a duration, only a rate, so fit is a measurement: synthesise at a
 * default rate, and if the take overruns its caption window, re-synthesise faster. Capped, because a
 * line read at 260 wpm is not a line anyone hears. */
function synth(line: Line, dest: string): void {
  let rate = Number(process.env.NARRATE_RATE ?? 178);
  for (let attempt = 0; attempt < 3; attempt++) {
    execFileSync("say", ["-v", SAY_VOICE, "-r", String(rate), "-o", dest, line.text]);
    const d = duration(dest);
    if (d <= line.window + 0.35 || rate >= 240) return;
    rate = Math.min(240, Math.round(rate * Math.min(1.35, (d / (line.window + 0.2)) * 1.02)));
  }
}

const parts: { file: string; at: number }[] = [];
let overruns = 0;
for (const line of lines) {
  const stem = String(line.i).padStart(2, "0");
  const take = recordedTake(line.i);
  const wav = join(WORK, `${stem}.wav`);
  if (take) {
    execFileSync(ffmpeg, ["-v", "error", "-y", "-i", take, "-ac", "2", "-ar", "44100", wav]);
  } else {
    const aiff = join(WORK, `${stem}.aiff`);
    synth(line, aiff);
    execFileSync(ffmpeg, ["-v", "error", "-y", "-i", aiff, "-ac", "2", "-ar", "44100", wav]);
  }
  const d = duration(wav);
  if (d > line.window + 0.35) overruns++;
  parts.push({ file: wav, at: line.at });
}

/* One amix over every line, each delayed to its cue. `normalize=0` because amix's default divides by
 * the number of inputs, which on 40-odd mostly-silent-at-any-instant inputs is near-total attenuation.
 * `dropout_transition` off for the same reason: gain must not move when a line ends. */
const args: string[] = ["-v", "error", "-y", "-i", VIDEO_IN];
for (const p of parts) args.push("-i", p.file);
const chains = parts.map((p, n) => `[${n + 1}:a]adelay=${Math.round(p.at * 1000)}|${Math.round(p.at * 1000)}[a${n}]`);
const mixIn = parts.map((_, n) => `[a${n}]`).join("");
/* `apad` and an explicit `-t`, not `-shortest`: the last line ends before the last frame does, and
 * `-shortest` would cut nine seconds of picture off the end to match the audio. */
const videoDur = duration(VIDEO_IN);
const filter = `${chains.join(";")};${mixIn}amix=inputs=${parts.length}:normalize=0:dropout_transition=0[mixed];[mixed]alimiter=limit=0.94,aresample=48000,apad[aout]`;
args.push(
  "-filter_complex", filter,
  "-map", "0:v", "-map", "[aout]",
  "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",
  "-t", videoDur.toFixed(3), VIDEO_OUT,
);
execFileSync(ffmpeg, args, { stdio: ["ignore", "inherit", "inherit"] });

const recorded = lines.filter((l) => recordedTake(l.i)).length;
console.log(
  `narrated  ${VIDEO_OUT.replace(ROOT + "/", "")}  ${duration(VIDEO_OUT).toFixed(1)}s  ` +
    `${lines.length} lines (${recorded} recorded, ${lines.length - recorded} synthesised, ${overruns} over window)`,
);
