/**
 * Export a real signed report for the Solidity consumer to verify.
 *
 * The point of this file is interoperability, and it only proves interoperability
 * because of what it does *not* do: it does not describe the wire format to the
 * Solidity side, and the Solidity side does not import anything from here. This writes
 * the bytes the TypeScript producer actually emits — the payload from the enclave's
 * local run against live subgraph data, wrapped in the CRE header, hashed and signed —
 * and `contracts/test/SentinelConsumer.t.sol` decodes them with an implementation
 * written from `docs/SIGNAL.md` alone.
 *
 * So a disagreement between the two is a real finding: either the doc is ambiguous or
 * one implementation is wrong. A fixture generated by the same code that reads it
 * could not tell us that.
 *
 * `expected` carries the TypeScript decode of the same bytes, so the Solidity test can
 * assert field by field rather than merely "it parsed".
 *
 *   npm run fixture:report
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { toHex, type Address, type Hex } from "viem";
import {
  buildRawReport,
  buildReportContext,
  devSigningKeys,
  signerAddress,
  signReport,
} from "../lib/signal/dev-sign";
import { decodeSignal } from "../lib/signal/report";
import { reportBody } from "../lib/signal/consume";

const LOG = "docs/evidence/enclave-local-run.log";
const OUT = "contracts/test/fixtures/report.json";

/** Same extraction as `scripts/consume-signal.mts`: the real payload, not a constructed one. */
function payloadFromLog(path: string): Hex {
  const lines = readFileSync(path, "utf8").split("\n");
  const marker = lines.findIndex((l) => l.includes("report that would cross the enclave boundary"));
  if (marker < 0) throw new Error(`no report payload in ${path}; re-run the enclave harness first`);
  const base64 = lines[marker + 1]?.trim();
  if (!base64) throw new Error(`report payload line is empty in ${path}`);
  return toHex(Buffer.from(base64, "base64"));
}

// Four signers with f = 1: quorum is two, and the extra two give the negative tests
// room to demonstrate that a short quorum is refused rather than rounded down.
const KEYS = devSigningKeys(4);
const WORKFLOW_NAME = "sentinel";
const OWNER: Address = "0x00000000000000000000000000000000000000a1";
const CONFIG_DIGEST: Hex = `0x${"33".repeat(32)}`;
const SEQ_NR = 7n;

async function main() {
  const body = payloadFromLog(LOG);
  const rawReport = buildRawReport({
    workflowName: WORKFLOW_NAME,
    workflowOwner: OWNER,
    body,
    // Pinned rather than `Date.now()`: a fixture that changes on every run would make
    // the Solidity test's expected values unstable for no reason.
    timestamp: 1_760_000_000,
  });
  const context = buildReportContext(CONFIG_DIGEST, SEQ_NR);
  const signed = await signReport(rawReport, context, KEYS.slice(0, 2));
  const signal = decodeSignal(reportBody(rawReport));

  const fixture = {
    _comment:
      "Generated by npm run fixture:report. Real signal body from a live enclave run; " +
      "signatures are throwaway dev keys, because the DON cannot sign a workflow that " +
      "is not yet deployed. Keys are in lib/signal/dev-sign.ts and must never be reused.",
    rawReport: toHex(signed.rawReport),
    reportContext: toHex(signed.reportContext),
    signatures: signed.signatures.map((s) => toHex(s)),
    // A third, valid signature from a signer outside the quorum used above. The test
    // needs one to show that a duplicate does not count while a distinct one does.
    thirdSignature: toHex((await signReport(rawReport, context, [KEYS[2]])).signatures[0]),
    signers: KEYS.map(signerAddress),
    f: "1",
    workflowOwner: OWNER,
    workflowName: WORKFLOW_NAME,
    // Every number as a decimal string: `vm.parseJsonUint` is inconsistent about wide
    // JSON numbers, and `vm.parseUint` on a string is unambiguous at any width.
    expected: {
      version: signal.version,
      asOfBlock: String(signal.asOfBlock),
      borrowersObserved: String(signal.borrowersObserved),
      debtUsd6: String(signal.debtUsd6),
      evaluableDebtUsd6: String(signal.evaluableDebtUsd6),
      multiProtocolDebtUsd6: String(signal.multiProtocolDebtUsd6),
      multiProtocolShareBps: String(signal.multiProtocolShareBps),
      leveredShareBps: String(signal.leveredShareBps),
      worstShockBps: String(signal.worstShockBps),
      worstShockDistressedDebtUsd6: String(signal.worstShockDistressedDebtUsd6),
      systemicRiskScoreBps: String(signal.systemicRiskScoreBps),
      couplingBuckets: String(signal.couplingBuckets),
      suppressedBuckets: String(signal.suppressedBuckets),
      emodeInferredBorrowers: String(signal.emodeInferredBorrowers),
      emodeInferredDebtUsd6: String(signal.emodeInferredDebtUsd6),
    },
  };

  mkdirSync("contracts/test/fixtures", { recursive: true });
  writeFileSync(OUT, `${JSON.stringify(fixture, null, 2)}\n`);
  console.log(
    `wrote ${OUT}: ${signed.rawReport.length}-byte report, ` +
      `${signed.signatures.length} signatures, block ${signal.asOfBlock}`,
  );
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
